# Generated by Django 5.1.1 on 2024-09-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialInsight', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='category',
        ),
        migrations.AlterField(
            model_name='messages',
            name='attribute',
            field=models.CharField(choices=[('empathy', '共感力'), ('organization', '組織理解'), ('influence', '影響力'), ('visioning', 'ビジョニング'), ('team', 'チームワーク力'), ('inspiration', '啓発力'), ('perseverance', '忍耐力'), ('total', '合計点')], max_length=20),
        ),
        migrations.AlterField(
            model_name='qanda',
            name='attribute',
            field=models.CharField(choices=[('empathy', '共感力'), ('organization', '組織理解'), ('influence', '影響力'), ('visioning', 'ビジョニング'), ('team', 'チームワーク力'), ('inspiration', '啓発力'), ('perseverance', '忍耐力'), ('total', '合計点')], max_length=20),
        ),
    ]
