# Generated by Django 5.1.1 on 2024-09-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialInsight', '0003_remove_messages_improvement_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qanda',
            name='status',
            field=models.CharField(choices=[('completed', '完了'), ('canceled', '中止')], default='canceled', max_length=10),
        ),
        migrations.AlterField(
            model_name='messages',
            name='attribute',
            field=models.CharField(choices=[('empathy', '共感力'), ('organization', '組織理解'), ('visioning', 'ビジョニング'), ('influence', '影響力'), ('inspiration', '啓発力'), ('team', 'チームワーク力'), ('perseverance', '忍耐力'), ('total', '合計点')], max_length=20),
        ),
        migrations.AlterField(
            model_name='qanda',
            name='attribute',
            field=models.CharField(choices=[('empathy', '共感力'), ('organization', '組織理解'), ('visioning', 'ビジョニング'), ('influence', '影響力'), ('inspiration', '啓発力'), ('team', 'チームワーク力'), ('perseverance', '忍耐力'), ('total', '合計点')], max_length=20),
        ),
    ]
