# Generated by Django 5.1.1 on 2024-09-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialInsight', '0005_remove_qanda_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='qanda',
            name='status',
            field=models.CharField(choices=[('completed', '完了'), ('canceled', '中止')], default='canceled', max_length=10),
        ),
    ]
