# Generated by Django 5.1.1 on 2024-09-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialInsight', '0006_qanda_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qanda',
            name='status',
        ),
    ]
