# Generated by Django 5.1.1 on 2024-09-05 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.RemoveField(
            model_name='scores',
            name='user',
        ),
        migrations.DeleteModel(
            name='QandA',
        ),
        migrations.DeleteModel(
            name='Scores',
        ),
    ]
