# Generated by Django 5.1.6 on 2025-02-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialInsight', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_part_time_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('high_schooler', '高校生'), ('undergrad', '大学生'), ('worker', '社会人')], default='high_schooler', max_length=20),
        ),
    ]
