# Generated by Django 5.1.6 on 2025-02-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialInsight', '0005_profile_has_part_time_job_alter_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
